### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by ajaykr089** [edfuh/bootypicker#1]
Hi,

Thanks for the library, i was trying to use your library in my project, but it seems some dependency of jQuery library

<img width="1231" alt="screen shot 2017-05-26 at 10 20 28 pm" src="https://cloud.githubusercontent.com/assets/2228177/26504291/a0a79766-4261-11e7-8371-64f0c153a378.png">
`https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.2/jquery.min.js`

**Comment by edfuh** [comment]
yes, jQuery is required

**Comment by ajaykr089** [comment]
Yes, which i have added already as you can see in the screenshot,
Leave it BTW, i have used something else,

Thanks for your reply :)
